export const sampleExercises = [
  {
    id: 1,
    name: "Push-Up",
    description: "A basic upper body exercise to strengthen chest, shoulders, and triceps.",
    category: "strength",
    intensity: "moderate",
    suitableForSex: "both",
    reps: 15,
    sets: 3,
    duration: 5,
    imageDescription: "Person doing a push-up.",
    targetAreas: ["chest", "shoulders", "triceps"],
    images: ["https://example.com/push-up.jpg"],
    caloriesBurned: 50,
    goalType: ["Building Muscle"],
    fitnessLevel: "beginner",
    bmiRange: { min: 18.5, max: 30 },
    ageRange: { min: 12, max: 60 }
  },
  {
    id: 2,
    name: "Jump Rope",
    description: "A cardio exercise to improve heart rate and burn calories.",
    category: "cardio",
    intensity: "high",
    suitableForSex: "both",
    reps: null,
    sets: null,
    duration: 10,
    imageDescription: "Person jumping rope.",
    targetAreas: ["legs", "core"],
    images: ["https://example.com/jump-rope.jpg"],
    caloriesBurned: 100,
    goalType: ["Weight Loss"],
    fitnessLevel: "intermediate",
    bmiRange: { min: 18.5, max: 25 },
    ageRange: { min: 15, max: 50 }
  },
  {
    id: 3,
    name: "Squats",
    description: "A lower body exercise focusing on legs and glutes.",
    category: "strength",
    intensity: "moderate",
    suitableForSex: "both",
    reps: 20,
    sets: 4,
    duration: 8,
    imageDescription: "Person doing squats.",
    targetAreas: ["legs", "glutes"],
    images: ["https://example.com/squats.jpg"],
    caloriesBurned: 80,
    goalType: ["Building Muscle"],
    fitnessLevel: "beginner",
    bmiRange: { min: 18, max: 30 },
    ageRange: { min: 15, max: 50 }
  },
  {
    id: 4,
    name: "Plank",
    description: "Core strengthening exercise to build endurance and stability.",
    category: "core",
    intensity: "moderate",
    suitableForSex: "both",
    reps: null,
    sets: 3,
    duration: 3,
    imageDescription: "Person holding a plank position.",
    targetAreas: ["core"],
    images: ["https://example.com/plank.jpg"],
    caloriesBurned: 30,
    goalType: ["Building Endurance"],
    fitnessLevel: "intermediate",
    bmiRange: { min: 18.5, max: 28 },
    ageRange: { min: 12, max: 60 }
  },
  {
    id: 5,
    name: "Lunges",
    description: "A lower body exercise that improves balance and strengthens legs.",
    category: "strength",
    intensity: "moderate",
    suitableForSex: "both",
    reps: 15,
    sets: 3,
    duration: 7,
    imageDescription: "Person doing lunges.",
    targetAreas: ["legs", "glutes"],
    images: ["https://example.com/lunges.jpg"],
    caloriesBurned: 70,
    goalType: ["Toning"],
    fitnessLevel: "beginner",
    bmiRange: { min: 18, max: 30 },
    ageRange: { min: 15, max: 55 }
  },
  {
    id: 6,
    name: "Bicycle Crunch",
    description: "An abdominal exercise that engages obliques and core.",
    category: "core",
    intensity: "moderate",
    suitableForSex: "both",
    reps: 20,
    sets: 3,
    duration: 5,
    imageDescription: "Person doing bicycle crunches.",
    targetAreas: ["core", "obliques"],
    images: ["https://example.com/bicycle-crunch.jpg"],
    caloriesBurned: 60,
    goalType: ["Core Strength"],
    fitnessLevel: "intermediate",
    bmiRange: { min: 18.5, max: 28 },
    ageRange: { min: 18, max: 50 }
  },
  {
    id: 7,
    name: "Mountain Climbers",
    description: "A cardio-intensive core workout.",
    category: "cardio",
    intensity: "high",
    suitableForSex: "both",
    reps: 30,
    sets: 4,
    duration: 5,
    imageDescription: "Person performing mountain climbers.",
    targetAreas: ["core", "legs"],
    images: ["https://example.com/mountain-climbers.jpg"],
    caloriesBurned: 120,
    goalType: ["Weight Loss"],
    fitnessLevel: "intermediate",
    bmiRange: { min: 18, max: 30 },
    ageRange: { min: 18, max: 45 }
  },
  {
    id: 8,
    name: "Burpees",
    description: "A full-body exercise for high-intensity interval training.",
    category: "HIIT",
    intensity: "high",
    suitableForSex: "both",
    reps: 15,
    sets: 3,
    duration: 5,
    imageDescription: "Person doing burpees.",
    targetAreas: ["full body"],
    images: ["https://example.com/burpees.jpg"],
    caloriesBurned: 150,
    goalType: ["Weight Loss"],
    fitnessLevel: "advanced",
    bmiRange: { min: 18, max: 28 },
    ageRange: { min: 18, max: 40 }
  },
  {
    id: 9,
    name: "Bench Press",
    description: "A strength exercise focused on chest and arms.",
    category: "strength",
    intensity: "high",
    suitableForSex: "both",
    reps: 10,
    sets: 3,
    duration: 8,
    imageDescription: "Person performing bench press.",
    targetAreas: ["chest", "arms"],
    images: ["https://example.com/bench-press.jpg"],
    caloriesBurned: 90,
    goalType: ["Building Muscle"],
    fitnessLevel: "intermediate",
    bmiRange: { min: 18, max: 30 },
    ageRange: { min: 18, max: 60 }
  },
  {
    id: 10,
    name: "Russian Twist",
    description: "A core workout targeting the obliques.",
    category: "core",
    intensity: "moderate",
    suitableForSex: "both",
    reps: 25,
    sets: 3,
    duration: 4,
    imageDescription: "Person doing Russian twists.",
    targetAreas: ["core", "obliques"],
    images: ["https://media1.popsugar-assets.com/files/thumbor/uHT66rs8CK8XlYQBpMJOUDglGW0=/fit-in/792x544/top/filters:format_auto():upscale()/2024/01/02/752/n/1922729/3300e166ea0ccfe2_PS23_Fitness_Workout_14_Move_10_Russian_Twist_Alt.jpg"],
    caloriesBurned: 50,
    goalType: ["Core Strength"],
    fitnessLevel: "intermediate",
    bmiRange: { min: 18, max: 28 },
    ageRange: { min: 15, max: 50 }
  }
];
