export const sampleExercises = [
  {
    id: 1,
    name: "Push-Up",
    description: "A basic upper body exercise to strengthen chest, shoulders, and triceps.",
    category: "strength",
    intensity: "moderate",
    suitableForSex: "both",
    reps: 15,
    sets: 3,
    duration: 5,
    imageDescription: "Person doing a push-up.",
    targetAreas: ["chest", "shoulders", "triceps"],
    images: ["https://cdn.centr.com/content/31000/30074/images/landscapewidemobile1x-unleashed-lz-aj-dc-tricep-push-up.jpg"],
    caloriesBurned: 50,
    goalType: ["Building Muscle"],
    fitnessLevel: "beginner",
    bmiRange: { min: 18.5, max: 30 },
    ageRange: { min: 12, max: 60 }
  },
  {
    id: 2,
    name: "Jump Rope",
    description: "A cardio exercise to improve heart rate and burn calories.",
    category: "cardio",
    intensity: "high",
    suitableForSex: "both",
    reps: null,
    sets: null,
    duration: 10,
    imageDescription: "Person jumping rope.",
    targetAreas: ["legs", "core"],
    images: ["https://wockhardthospital.b-cdn.net/wp-content/uploads/2021/07/Jumping-Ropes-768x512-1.webp"],
    caloriesBurned: 100,
    goalType: ["Weight Loss"],
    fitnessLevel: "intermediate",
    bmiRange: { min: 18.5, max: 25 },
    ageRange: { min: 15, max: 50 }
  },
  {
    id: 3,
    name: "Squats",
    description: "A lower body exercise focusing on legs and glutes.",
    category: "strength",
    intensity: "moderate",
    suitableForSex: "both",
    reps: 20,
    sets: 4,
    duration: 8,
    imageDescription: "Person doing squats.",
    targetAreas: ["legs", "glutes"],
    images: ["https://cdn.shopify.com/s/files/1/0386/9569/8572/files/Kettlebell_Squat_1_d5d6f890-38d8-479a-8031-19c0a719547a_1024x1024.jpg?v=1625217770"],
    caloriesBurned: 80,
    goalType: ["Building Muscle"],
    fitnessLevel: "beginner",
    bmiRange: { min: 18, max: 30 },
    ageRange: { min: 15, max: 50 }
  },
  {
    id: 4,
    name: "Plank",
    description: "Core strengthening exercise to build endurance and stability.",
    category: "core",
    intensity: "moderate",
    suitableForSex: "both",
    reps: null,
    sets: 3,
    duration: 3,
    imageDescription: "Person holding a plank position.",
    targetAreas: ["core"],
    images: ["https://mirafit.co.uk/wp/wp-content/uploads/2021/03/Mirafit-Perfect-Plank-1024x614.jpg"],
    caloriesBurned: 30,
    goalType: ["Building Endurance"],
    fitnessLevel: "intermediate",
    bmiRange: { min: 18.5, max: 28 },
    ageRange: { min: 12, max: 60 }
  },
  {
    id: 5,
    name: "Lunges",
    description: "A lower body exercise that improves balance and strengthens legs.",
    category: "strength",
    intensity: "moderate",
    suitableForSex: "both",
    reps: 15,
    sets: 3,
    duration: 7,
    imageDescription: "Person doing lunges.",
    targetAreas: ["legs", "glutes"],
    images: ["https://images.healthshots.com/healthshots/en/uploads/2024/05/02174153/Lunges.jpg"],
    caloriesBurned: 70,
    goalType: ["Toning"],
    fitnessLevel: "beginner",
    bmiRange: { min: 18, max: 30 },
    ageRange: { min: 15, max: 55 }
  },
  {
    id: 6,
    name: "Bicycle Crunch",
    description: "An abdominal exercise that engages obliques and core.",
    category: "core",
    intensity: "moderate",
    suitableForSex: "both",
    reps: 20,
    sets: 3,
    duration: 5,
    imageDescription: "Person doing bicycle crunches.",
    targetAreas: ["core", "obliques"],
    images: ["https://images.ctfassets.net/hjcv6wdwxsdz/4Mh1bGGIUDoXmCgch4HdwX/d1b81c635dddbfe3a2e28247324114ab/woman-doing-bicycle-crunch.png?w=1200"],
    caloriesBurned: 60,
    goalType: ["Core Strength"],
    fitnessLevel: "intermediate",
    bmiRange: { min: 18.5, max: 28 },
    ageRange: { min: 18, max: 50 }
  },
  {
    id: 7,
    name: "Mountain Climbers",
    description: "A cardio-intensive core workout.",
    category: "cardio",
    intensity: "high",
    suitableForSex: "both",
    reps: 30,
    sets: 4,
    duration: 5,
    imageDescription: "Person performing mountain climbers.",
    targetAreas: ["core", "legs"],
    images: ["https://www.shape.com/thmb/vjcnj9JvFVq1AAgujIvcMV_W4xQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/how-to-do-mountain-climbers-promo-2000-84383ce1700e4b2b94dc2a8a0d245b71.jpg"],
    caloriesBurned: 120,
    goalType: ["Weight Loss"],
    fitnessLevel: "intermediate",
    bmiRange: { min: 18, max: 30 },
    ageRange: { min: 18, max: 45 }
  },
  {
    id: 8,
    name: "Burpees",
    description: "A full-body exercise for high-intensity interval training.",
    category: "HIIT",
    intensity: "high",
    suitableForSex: "both",
    reps: 15,
    sets: 3,
    duration: 5,
    imageDescription: "Person doing burpees.",
    targetAreas: ["full body"],
    images: ["https://images.squarespace-cdn.com/content/v1/640626ced6468757ca7fc2f7/1719792911953-QMRFLS1PJZXU336F6S1N/what-to-do-if-you-hate-burpees.jpg"],
    caloriesBurned: 150,
    goalType: ["Weight Loss"],
    fitnessLevel: "advanced",
    bmiRange: { min: 18, max: 28 },
    ageRange: { min: 18, max: 40 }
  },
  {
    id: 9,
    name: "Bench Press",
    description: "A strength exercise focused on chest and arms.",
    category: "strength",
    intensity: "high",
    suitableForSex: "both",
    reps: 10,
    sets: 3,
    duration: 8,
    imageDescription: "Person performing bench press.",
    targetAreas: ["chest", "arms"],
    images: ["https://www.anytimefitness.com/wp-content/uploads/2024/01/AF-HERO_BenchPress-1024x683.jpg"],
    caloriesBurned: 90,
    goalType: ["Building Muscle"],
    fitnessLevel: "intermediate",
    bmiRange: { min: 18, max: 30 },
    ageRange: { min: 18, max: 60 }
  },
  {
    id: 10,
    name: "Russian Twist",
    description: "A core workout targeting the obliques.",
    category: "core",
    intensity: "moderate",
    suitableForSex: "both",
    reps: 25,
    sets: 3,
    duration: 4,
    imageDescription: "Person doing Russian twists.",
    targetAreas: ["core", "obliques"],
    images: ["https://cdn.mos.cms.futurecdn.net/yTVgqM7RBHk8FsVVF9dp5D.jpg"],
    caloriesBurned: 50,
    goalType: ["Core Strength"],
    fitnessLevel: "intermediate",
    bmiRange: { min: 18, max: 28 },
    ageRange: { min: 15, max: 50 }
  }
];
